---
# Parallel processing set up
run_parallel: 1
nprocesses: 128  # Number of processors to use if run_parallel=1
dask_tmp_dir: '/tmp'

# Start/end date and time
startdate: '20190201.0000'
enddate: '20190302.0000'

root_dir: '/pscratch/sd/f/feng045/SAAG/hist/auxhist/'
out_dir: '/pscratch/sd/f/feng045/SAAG/hist/auxhist/refl/'
in_basename: 'auxhist_d01_'
out_basenbame: 'refl_'
# Constant file
map_file: '/pscratch/sd/f/feng045/SAAG/hist/maps/wrfconstants_SAAG_20yr.nc'

# Specify input data date/time string format
# E.g., databasename20181101.011503.nc --> yyyymodd.hhmmss
# E.g., databasename2018-11-01_01:15:00 --> yyyy-mo-dd_hh:mm:ss
time_format: 'yyyy-mo-dd_hh:mm:ss'

# # Variable list to subset
pass_varname:
  - 'REFL_COM'
#   - 'OLR'

# Subset domain
center_lon: -64.75
center_lat: -32.1
subset_width: 2.0  # [degree]

lonmin: -66.25
lonmax: -62.25
latmin: -34.10
latmax: -30.10

# Variable names in the output data
time_dimname: 'time'
x_dimname: 'lon'
y_dimname: 'lat'
time_coordname: 'time'
x_coordname: 'longitude'
y_coordname: 'latitude'
tb_varname: 'tb'
pcp_varname: 'rainrate'